export { buildHeroDeckPreview } from "./deckPreview.js";
export { applyCommand } from "./engine.js";
export { createInitialSnapshot, createFoundingSnapshot, createFoundingParty, createHero, deriveHeroPools } from "./state.js";
export { createNamedRngStates, drawInt, drawUnit, shuffle } from "./rng.js";
export { startCombat, applyCombatCommand, refillForFixture, reviveForFixture, syncHeroesFromCombat, totalBlockForFixture, intentEffectSummary } from "./combat.js";
export { finishCombatIfNeeded, wipe } from "./expedition.js";
export { hashResolvedFacts } from "./facts.js";
export { createItemInstance, enrichItemDisplay, rarityFromUnit } from "./items.js";
export { legendaryEligibleDefinitionIds, rollGearAffixIds, signatureForDefinition } from "./loot.js";
export { cloneSnapshot, createContext } from "./internal.js";
export type { ForcedStreams, MutableSnapshot, SimulationContext } from "./internal.js";
